export const mechanism = [
  {
    src: '/images/EP10.webp',
    alt: 'Picture 1',
    title: 'Mehanizam EP 10 nosivosti od 25kg do 70kg',
    filler: 'Staklo 4mm, drvo 10 ili 18mm',
    thickness: '-',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP18.webp',
    alt: 'Picture 2',
    title: 'Mehanizam EP 18 N nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '-',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP04.webp',
    alt: 'Picture 3',
    title: 'Mehanizam EP 04 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 10 ili 18mm',
    thickness: '-',
    doorWidth: '50cm - 120cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/PKM80.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP18.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/PKM80.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP10.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/PKM80.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP18.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP10.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/PKM80.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
  {
    src: '/images/EP18.webp',
    alt: 'Picture 4',
    title: 'Mehanizam PKM 80 nosivosti od 15kg do 60kg',
    filler: 'Staklo 4mm, drvo 18mm',
    thickness: '18mm',
    doorWidth: '50cm - 140cm',
    doorHeight: '30cm - 320cm',
  },
];
